apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret-credentials
data:
  username: YWRtaW4K
  password: cGFzc3dkCg==
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-simple-secret-mount
spec:
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
        - name: simple-secret-credentials
          mountPath: /tmp/
      ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
  volumes:
    - name: simple-secret-credentials
      secret:
        secretName: nginx-secret-credentials

