apiVersion: v1
data:
  env-secret.conf: dXNlcm5hbWU6IFlXUnRhVzRLCnBhc3N3b3JkOiBjR0Z6YzNka0NnPT0K
  # kubectl create secret generic nginx-credentials-from-file --from-file=env-secret.conf --dry-run --output yaml | tee secret_from_file.yaml
kind: Secret
metadata:
  name: nginx-credentials-from-file
---
apiVersion: v1
data:
  env-secret_1.conf: dXNlcm5hbWU6IFlXUnRhVzRLCg==
  env-secret_2.conf: cGFzc3dvcmQ6IGNHRnpjM2RrQ2c9PQo=
  # kubectl create secret generic nginx-credentials-from-file --from-file=env-secret_1.conf --from-file=env-secret_2.conf --dry-run --output yaml | tee secret_from_multiple_files.yaml
kind: Secret
metadata:
  creationTimestamp: null
  name: nginx-credentials-from-multiple-file
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-secret-from-file
spec:
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
        - name: secret-credentials-from-file
          mountPath: /tmp/
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: nginx-credentials-from-multiple-file
              key: env-secret_1.conf
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nginx-credentials-from-multiple-file
              key: env-secret_2.conf           
      ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
  volumes:
    - name: secret-credentials-from-file
      secret:
        secretName: nginx-credentials-from-file
