apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2M
  hostPath:
    path: "/tmp/data01"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1M
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-pvc
  labels:
    app : nginx-with-pvc
spec:
  volumes:
    - name: my-pvc
      persistentVolumeClaim:
        claimName: pv-claim
  containers:
    - name: nginx
      image: nginx
