apiVersion: v1
data:
  env-secret_1.conf: dXNlcm5hbWU6IFlXUnRhVzRLCg==
  env-secret_2.conf: cGFzc3dvcmQ6IGNHRnpjM2RrQ2c9PQo=
kind: Secret
metadata:
  creationTimestamp: null
  name: nginx-credentials-from-multiple-file
