apiVersion: v1
kind: Pod
metadata:
  name: tcp-liveness-readiness-example
  # Using tcpSocket option, kubelet will attempt to open a socket to your container on the specified port. 
  # If it can establish a connection, the container is considered healthy, if it can’t it is considered a failure.
spec:
  containers:
  - name: goproxy-container
    image: k8s.gcr.io/goproxy:0.1
    ports:
    - containerPort: 8080
    # attempt to connect to the goproxy container on port 8080
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
    # attempt to connect to the goproxy container on port 8080
    livenessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 20
