apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-storageclass-local
spec:
  storageClassName: local-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2M