apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-hostpath-storageclass-local
  labels:
    type: local
spec:
  storageClassName: local-storage-class
  capacity:
    storage: 10M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"