apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-hostpath
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"