apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svc_name}}
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: {{ .Values.service.port}}
      targetPort: {{ .Values.service.targetPort}}
